### ISSUE TITLE
Segmentfault

### ISSUE THREAD

**Issue by myfreess** [lexdene/tieba-post-to-epub#1]
tieba-to-epub 4949361390 dark.epub
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/tieba-to-epub", line 11, in <module>
    load_entry_point('tieba-to-epub==0.0.3', 'console_scripts', 'tieba-to-epub')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/main.py", line 51, in main
    loop.run_until_complete(_main())
  File "/data/data/com.termux/files/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/main.py", line 46, in _main
    await b.run()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/builders/epub.py", line 28, in run
    async for page in self.iter_pages():
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/builders/base.py", line 43, in iter_pages
    page = await self.get_page(session, path, params, page_num)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/builders/base.py", line 80, in get_page
    session,
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/builders/base.py", line 107, in _trans_image_node
    async with session.get(url, headers={'User-Agent': USER_AGENT}) as resp:
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 951, in _create_direct_connection
    assert port is not None
AssertionError

**Comment by myfreess** [comment]
环境:Termux,Android6.0,python3.7.2
aiohttp 3.5.4

**Comment by lexdene** [comment]
pip install -U tieba-to-epub

and try again.
