### ISSUE TITLE
在对部分帖子进行转换时出现error

### ISSUE THREAD

**Issue by myfreess** [lexdene/tieba-post-to-epub#5]
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/tieba-to-epub", line 11, in <module>
    load_entry_point('tieba-to-epub==0.0.4', 'console_scripts', 'tieba-to-epub')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/main.py", line 51, in main
    loop.run_until_complete(_main())
  File "/data/data/com.termux/files/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/main.py", line 46, in _main
    await b.run()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/builders/epub.py", line 28, in run
    async for page in self.iter_pages():
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/builders/base.py", line 43, in iter_pages
    page = await self.get_page(session, path, params, page_num)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/builders/base.py", line 72, in get_page
    page = parse_page(text)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/parsers.py", line 51, in parse_page
    '//div[contains(concat(" ", @class, " "), " d_post_content_main ")]'  # noqa
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/parsers.py", line 50, in <listcomp>
    for ele in doc.xpath(
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/parsers.py", line 72, in parse_floor
    iter_node_from_floor(ele)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/parsers.py", line 82, in iter_node_from_floor
    for node in iter_node_from_content(content_ele):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tieba_to_epub/parsers.py", line 136, in iter_node_from_content
    ele.tag, event, text
ValueError: unexpected tag: span when start with text 1

```

**Comment by myfreess** [comment]
另外新年快乐!

**Comment by myfreess** [comment]
附上贴子链接

https://tieba.baidu.com/p/4464857632

**Comment by lexdene** [comment]
抱歉刚看见。我不确定我近期会有时间解决这个问题。

**Comment by myfreess** [comment]
没关系 @lexdene

**Comment by lexdene** [comment]
```
pip install -U tieba-to-epub
```

and try again.
